#
# Description: Auto update package
#
name: "T3 test"

on:
  push:
    paths:
      - '.github/workflows/Test.v3.yml'
  schedule:
    - cron: "0 */16 * * *"
  workflow_dispatch:
    inputs:
      packages:
        description: 'packages'
        required: false
        default: ''
permissions:
  contents: write
    
env:
  TZ: Asia/Shanghai

jobs:
  job_init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'main'

      - name: Initialization environment
        run: |
          sudo timedatectl set-timezone "$TZ"

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
        
      - name: SSH connection to Actions
        uses: mxschmitt/action-tmate@master
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

  job_update_packages:
    if: ${{ always() }}
    needs: job_init
    runs-on: ubuntu-latest
    name: update-${{ matrix.pakcages }} 
    strategy:
      fail-fast: false
      matrix:
        pakcages: [chinadns-ng@aarch64-linux-musl@generic+v8a@fast+lto, chinadns-ng@arm-linux-musleabi@generic+v7a@fast+lto, chinadns-ng@arm-linux-musleabihf@generic+v7a@fast+lto, chinadns-ng@mips-linux-musl@mips32@fast+lto, chinadns-ng@mipsel-linux-musl@mips32@fast+lto, chinadns-ng@i386-linux-musl@i686@fast+lto, chinadns-ng@x86_64-linux-musl@x86_64@fast+lto]
        include:
          - pakcages: chinadns-ng@aarch64-linux-musl@generic+v8a@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 16
          - pakcages: chinadns-ng@arm-linux-musleabi@generic+v7a@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 21
          - pakcages: chinadns-ng@arm-linux-musleabihf@generic+v7a@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 24
          - pakcages: chinadns-ng@mips-linux-musl@mips32@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 28
          - pakcages: chinadns-ng@mipsel-linux-musl@mips32@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 31
          - pakcages: chinadns-ng@i386-linux-musl@i686@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 34
          - pakcages: chinadns-ng@x86_64-linux-musl@x86_64@fast+lto
            folder: chinadns-ng
            version_line: 8
            hash_line: 36

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: 'main'

      - name: Initialization environment
        run: |
          cd && mkdir -p main && cd main
          sudo timedatectl set-timezone "$TZ"

      - name: Get versions and hashes
        id: get_versions_hashes
        run: |
          versions_hashes=$(curl -sL "https://api.github.com/repos/zfl9/chinadns-ng/releases" | jq -r '[.[] | {tag_name: .tag_name, assets: [.assets[] | {name: .name, hash: .browser_download_url}] }] | group_by(.tag_name) | .[] | {"version": .[0].tag_name, "hashes": [.[].assets]}')
          echo "versions_hashes=$versions_hashes" >> $GITHUB_ENV

      - name: Update ${{ matrix.pakcages }}
        run: |
          versions_hashes="${{ env.versions_hashes }}"
          for version_hash in $versions_hashes; do
            version=$(echo $version_hash | jq -r '.version')
            hashes=$(echo $version_hash | jq -r '.hashes[].hash')
            # Perform update for each package using version and hash
            # Add your update logic here
          done

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@master
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "${{ matrix.packages }}: update to ${{ env.version }}"
          branch: main